import { useCallback, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Image } from 'expo-image';
import { useFocusEffect, useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';

import { CastButton } from '@/components/CastButton';
import { HexagramView } from '@/components/HexagramView';
import { PremiumReadingText } from '@/components/PremiumReadingText';
import { ScreenContainer } from '@/components/ScreenContainer';
import { ShareHexagramButton } from '@/components/ShareHexagramButton';
import { usageLimits } from '@/config/usageLimits';
import { generatePremiumReading } from '@/core/aiReadings/client';
import { getAiReadingPersonality } from '@/core/aiReadings/personalities';
import { getCastLineDescription } from '@/core/iching/generate';
import { CastLineDetail, CompletedReading } from '@/core/iching/types';
import {
  clearCurrentReading,
  getCurrentReading,
  getTodaysPremiumAiReadingCount,
  recordPremiumAiReadingRequest,
  savePremiumReadingForToday,
} from '@/storage/readingsStorage';
import { useAppTheme } from '@/theme/appTheme';
import { AiChingColorPalette, getAiChingColors } from '@/theme/colors';
import { getAiReadingAvatarSource, getHexagramBackgroundSource } from '@/theme/hexagramBackgrounds';
import { formatReadingDate } from '@/utils/date';

const internetRequiredMessage = 'Internet connection required here. Please connect and retry.';

export default function PremiumReadingScreen() {
  const router = useRouter();
  const { aiReadingPersonalityId, colorMode, entitlements, themeId } = useAppTheme();
  const styles = usePremiumReadingStyles();
  const colors = getAiChingColors(colorMode);
  const scrollViewRef = useRef<ScrollView>(null);
  const [reading, setReading] = useState<CompletedReading | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [isPremiumDailyLimitReached, setIsPremiumDailyLimitReached] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const autoGeneratedReadingIdRef = useRef<string | null>(null);
  const isGeneratingRef = useRef(false);

  const generatePremiumReadingFor = useCallback(async (readingToGenerate: CompletedReading) => {
    if (isGeneratingRef.current) {
      return;
    }

    setErrorMessage(null);
    setIsPremiumDailyLimitReached(false);
    isGeneratingRef.current = true;
    setIsGenerating(true);

    try {
      const premiumReadingsToday = await getTodaysPremiumAiReadingCount();

      if (premiumReadingsToday >= usageLimits.premiumDailyAiReadingLimit) {
        setIsPremiumDailyLimitReached(true);
        throw new Error(
          'You have reached today\'s Premium reading limit. Please come back tomorrow for more AI-enhanced readings.',
        );
      }

      await recordPremiumAiReadingRequest();

      const premiumReading = await generatePremiumReading({
        hexagramNumber: readingToGenerate.hexagramNumber,
        lineCastDetails: readingToGenerate.lineCastDetails,
        personalityId: aiReadingPersonalityId,
        question: readingToGenerate.question,
        readingId: readingToGenerate.id,
        themeId,
      });
      const updatedReading = await savePremiumReadingForToday(premiumReading);
      setReading(updatedReading);
    } catch (error) {
      setErrorMessage(getPremiumReadingErrorMessage(error));
    } finally {
      isGeneratingRef.current = false;
      setIsGenerating(false);
    }
  }, [aiReadingPersonalityId, themeId]);

  useFocusEffect(
    useCallback(() => {
      getCurrentReading()
        .then((currentReading) => {
          setReading(currentReading);
          requestAnimationFrame(() => {
            scrollViewRef.current?.scrollTo({ y: 0, animated: false });
          });

          if (
            currentReading &&
            !currentReading.premiumReading &&
            autoGeneratedReadingIdRef.current !== currentReading.id
          ) {
            autoGeneratedReadingIdRef.current = currentReading.id;
            generatePremiumReadingFor(currentReading);
          }
        })
        .finally(() => setIsLoading(false));
    }, [generatePremiumReadingFor]),
  );

  const handleGeneratePremiumReading = useCallback(async () => {
    if (!reading) {
      return;
    }

    await generatePremiumReadingFor(reading);
  }, [generatePremiumReadingFor, reading]);

  async function handleAskAnotherQuestion() {
    await clearCurrentReading();
    router.replace({
      pathname: '/',
      params: {
        freshCast: String(Date.now()),
      },
    });
  }

  if (!entitlements.aiReadingsEnabled) {
    return (
      <ScreenContainer scroll={false} themeAware>
        <View style={styles.empty}>
          <Text style={styles.title}>Premium Reading</Text>
          <Text style={styles.body}>
            AI-enhanced readings are a premium feature. Manage your version to unlock them.
          </Text>
          <CastButton label="MANAGE VERSION" onPress={() => router.push('/version')} />
        </View>
      </ScreenContainer>
    );
  }

  if (isLoading) {
    return (
      <ScreenContainer scroll={false} themeAware>
        <View style={styles.centered}>
          <ActivityIndicator color={colors.gold} />
        </View>
      </ScreenContainer>
    );
  }

  if (!reading) {
    return (
      <ScreenContainer scroll={false} themeAware>
        <View style={styles.empty}>
          <Text style={styles.title}>No premium reading yet</Text>
          <Text style={styles.body}>Cast a hexagram to prepare an AI-enhanced reading.</Text>
          <CastButton label="CAST" onPress={() => router.push('/')} />
        </View>
      </ScreenContainer>
    );
  }

  const backgroundSource = getHexagramBackgroundSource(reading.hexagramNumber, themeId);
  const askedQuestion = reading.question?.trim();
  const selectedPersonality = getAiReadingPersonality(aiReadingPersonalityId);
  const aiReadingAvatarSource = getAiReadingAvatarSource(selectedPersonality.id, themeId);
  const premiumReading = reading.premiumReading;

  return (
    <View style={styles.backgroundScreen}>
      {backgroundSource ? (
        <Image source={backgroundSource} style={styles.backgroundImage} contentFit="cover" />
      ) : null}
      <View style={styles.imageScrim} />
      <SafeAreaView style={styles.readingSafeArea}>
        <ScrollView ref={scrollViewRef} contentContainerStyle={styles.readingContent}>
          <View style={styles.header}>
            <HexagramView lines={reading.lines} size="small" />
            <Text style={styles.date}>{formatReadingDate(reading.localDate)}</Text>
            <Text style={styles.title}>
              Premium Reading: Hexagram {reading.hexagramNumber}: {reading.hexagramName}
            </Text>
          </View>

          <View style={styles.card}>
            <Text style={styles.cardTitle}>
              Hexagram {reading.hexagramNumber}: {reading.hexagramName}
            </Text>
            {backgroundSource ? (
              <Image source={backgroundSource} style={styles.hexagramThemeImage} contentFit="cover" />
            ) : null}
          </View>

          {reading.lineCastDetails?.length ? (
            <CastingDetailsCard
              lineCastDetails={reading.lineCastDetails}
              resultingHexagramName={reading.resultingHexagramName}
              resultingHexagramNumber={reading.resultingHexagramNumber}
            />
          ) : null}

          <View style={styles.card}>
            <Text style={styles.cardTitle}>{askedQuestion ? 'Your Question' : 'General Outlook'}</Text>
            <Text style={styles.body}>
              {askedQuestion ??
                'You did not ask any particular question, so your reading will reflect a general outlook for you, much like a horoscope might provide.'}
            </Text>
          </View>

          <View style={styles.card}>
            <Text style={styles.cardTitle}>The Oracle Answers Here ...</Text>
            {premiumReading ? (
              <>
                {aiReadingAvatarSource ? (
                  <>
                    <Image
                      source={aiReadingAvatarSource}
                      style={styles.aiReadingAvatar}
                      contentFit="cover"
                    />
                    <Text style={styles.avatarCaption}>
                      Greetings, seeker. The {premiumReading.personalityName} avatar has considered
                      your question and offers a custom reading below.
                    </Text>
                  </>
                ) : null}
                <PremiumReadingText text={premiumReading.text} />
              </>
            ) : (
              <>
                <Text style={styles.body}>
                  The oracle is considering your question through {selectedPersonality.name}, this
                  hexagram, its reversed aspect, and its opposite.
                </Text>
                {errorMessage ? <Text style={styles.errorText}>{errorMessage}</Text> : null}
                {isPremiumDailyLimitReached ? null : isGenerating ? (
                  <View style={[styles.generateButton, styles.generateButtonDisabled]}>
                    <ActivityIndicator color={colors.ink} />
                    <Text style={styles.generateButtonText}>The Oracle Is Considering...</Text>
                  </View>
                ) : (
                  <Pressable
                    onPress={handleGeneratePremiumReading}
                    style={({ pressed }) => [styles.generateButton, pressed && styles.pressed]}>
                    <Text style={styles.generateButtonText}>
                      {errorMessage ? 'Try Again' : 'Generate Premium Reading'}
                    </Text>
                  </Pressable>
                )}
              </>
            )}
          </View>

          <CastButton label="ASK ANOTHER QUESTION" onPress={handleAskAnotherQuestion} />
          <ShareHexagramButton
            hexagramName={reading.hexagramName}
            hexagramNumber={reading.hexagramNumber}
            themeId={themeId}
          />
        </ScrollView>
      </SafeAreaView>
    </View>
  );
}

function getPremiumReadingErrorMessage(error: unknown): string {
  const message = error instanceof Error ? error.message : '';
  const normalizedMessage = message.toLowerCase();

  if (
    normalizedMessage.includes('fetch failed') ||
    normalizedMessage.includes('network request failed') ||
    normalizedMessage.includes('unknownhostexception') ||
    normalizedMessage.includes('unable to resolve host') ||
    normalizedMessage.includes('failed to fetch')
  ) {
    return internetRequiredMessage;
  }

  return message || 'Unable to generate the premium reading.';
}

function CastingDetailsCard({
  lineCastDetails,
  resultingHexagramName,
  resultingHexagramNumber,
}: {
  lineCastDetails: CastLineDetail[];
  resultingHexagramName?: string;
  resultingHexagramNumber?: number;
}) {
  const styles = usePremiumReadingStyles();
  const visibleLineDetails = [...lineCastDetails].reverse();

  return (
    <View style={styles.card}>
      <Text style={styles.cardTitle}>Casting Details</Text>
      <Text style={styles.body}>
        This reading used the traditional three-part casting flow. Each line was drawn from three
        values, then interpreted as 6, 7, 8, or 9.
      </Text>
      <View style={styles.castDetailList}>
        {visibleLineDetails.map((detail) => (
          <Text key={`cast-line-${detail.position}`} style={styles.castDetailItem}>
            Line {detail.position}: {getCastLineDescription(detail)}
          </Text>
        ))}
      </View>
      {resultingHexagramNumber && resultingHexagramName ? (
        <Text style={styles.changeNote}>
          Changing lines point toward Hexagram {resultingHexagramNumber}: {resultingHexagramName}.
        </Text>
      ) : (
        <Text style={styles.changeNote}>No changing lines appeared in this cast.</Text>
      )}
    </View>
  );
}

function usePremiumReadingStyles() {
  const { colorMode } = useAppTheme();

  return createPremiumReadingStyles(getAiChingColors(colorMode), colorMode);
}

function createPremiumReadingStyles(colors: AiChingColorPalette, colorMode: 'dark' | 'light') {
  const cardBackground = colorMode === 'dark' ? 'rgba(16, 19, 24, 0.72)' : 'rgba(255, 250, 240, 0.86)';
  const photoScrim = colorMode === 'dark' ? 'rgba(10, 12, 16, 0.58)' : 'rgba(247, 241, 231, 0.46)';

  return StyleSheet.create({
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  empty: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 18,
    padding: 24,
  },
  backgroundScreen: {
    flex: 1,
    backgroundColor: colors.ink,
  },
  backgroundImage: {
    ...StyleSheet.absoluteFill,
  },
  imageScrim: {
    ...StyleSheet.absoluteFill,
    backgroundColor: photoScrim,
  },
  readingSafeArea: {
    flex: 1,
  },
  readingContent: {
    flexGrow: 1,
    padding: 24,
    paddingBottom: 112,
    alignItems: 'center',
  },
  header: {
    alignItems: 'center',
    gap: 14,
    marginBottom: 24,
    width: '100%',
  },
  date: {
    color: colors.gold,
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  title: {
    color: colors.mist,
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    textAlign: 'center',
  },
  card: {
    width: '100%',
    maxWidth: 640,
    borderRadius: 8,
    backgroundColor: cardBackground,
    borderWidth: 1,
    borderColor: 'rgba(139, 93, 29, 0.24)',
    padding: 18,
    gap: 10,
    marginBottom: 18,
  },
  cardTitle: {
    color: colors.gold,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '800',
  },
  aiReadingAvatar: {
    width: '100%',
    aspectRatio: 1,
    borderRadius: 8,
    marginTop: 2,
    marginBottom: 6,
  },
  avatarCaption: {
    color: colors.mist,
    fontSize: 15,
    lineHeight: 22,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: 6,
  },
  hexagramThemeImage: {
    width: '100%',
    aspectRatio: 9 / 16,
    borderRadius: 8,
  },
  body: {
    color: colors.mist,
    fontSize: 16,
    lineHeight: 25,
    textAlign: 'center',
  },
  castDetailList: {
    gap: 6,
  },
  castDetailItem: {
    color: colors.mist,
    fontSize: 14,
    lineHeight: 20,
  },
  changeNote: {
    color: colors.gold,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
    textAlign: 'center',
  },
  errorText: {
    color: '#ffb4a8',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  generateButton: {
    minHeight: 52,
    borderRadius: 8,
    backgroundColor: colors.gold,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  generateButtonDisabled: {
    opacity: 0.72,
  },
  generateButtonText: {
    color: colors.ink,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  pressed: {
    opacity: 0.72,
  },
  });
}
