import { useCallback, useRef, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { Image } from 'expo-image';
import { useFocusEffect, useRouter } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';

import { CastButton } from '@/components/CastButton';
import { HexagramView } from '@/components/HexagramView';
import { PremiumReadingText } from '@/components/PremiumReadingText';
import { ScreenContainer } from '@/components/ScreenContainer';
import { generatePremiumReading } from '@/core/aiReadings/client';
import { getAiReadingPersonality } from '@/core/aiReadings/personalities';
import { CompletedReading } from '@/core/iching/types';
import { clearCurrentReading, getCurrentReading, savePremiumReadingForToday } from '@/storage/readingsStorage';
import { useAppTheme } from '@/theme/appTheme';
import { aiChingColors } from '@/theme/colors';
import { getHexagramBackgroundSource } from '@/theme/hexagramBackgrounds';
import { formatReadingDate } from '@/utils/date';

export default function PremiumReadingScreen() {
  const router = useRouter();
  const { aiReadingPersonalityId, entitlements, themeId } = useAppTheme();
  const scrollViewRef = useRef<ScrollView>(null);
  const [reading, setReading] = useState<CompletedReading | null>(null);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const autoGeneratedReadingIdRef = useRef<string | null>(null);
  const isGeneratingRef = useRef(false);

  const generatePremiumReadingFor = useCallback(async (readingToGenerate: CompletedReading) => {
    if (isGeneratingRef.current) {
      return;
    }

    setErrorMessage(null);
    isGeneratingRef.current = true;
    setIsGenerating(true);

    try {
      const premiumReading = await generatePremiumReading({
        hexagramNumber: readingToGenerate.hexagramNumber,
        personalityId: aiReadingPersonalityId,
        question: readingToGenerate.question,
        readingId: readingToGenerate.id,
      });
      const updatedReading = await savePremiumReadingForToday(premiumReading);
      setReading(updatedReading);
    } catch (error) {
      setErrorMessage(error instanceof Error ? error.message : 'Unable to generate the premium reading.');
    } finally {
      isGeneratingRef.current = false;
      setIsGenerating(false);
    }
  }, [aiReadingPersonalityId]);

  useFocusEffect(
    useCallback(() => {
      getCurrentReading()
        .then((currentReading) => {
          setReading(currentReading);
          requestAnimationFrame(() => {
            scrollViewRef.current?.scrollTo({ y: 0, animated: false });
          });

          if (
            currentReading &&
            !currentReading.premiumReading &&
            autoGeneratedReadingIdRef.current !== currentReading.id
          ) {
            autoGeneratedReadingIdRef.current = currentReading.id;
            generatePremiumReadingFor(currentReading);
          }
        })
        .finally(() => setIsLoading(false));
    }, [generatePremiumReadingFor]),
  );

  const handleGeneratePremiumReading = useCallback(async () => {
    if (!reading) {
      return;
    }

    await generatePremiumReadingFor(reading);
  }, [generatePremiumReadingFor, reading]);

  async function handleAskAnotherQuestion() {
    await clearCurrentReading();
    router.replace({
      pathname: '/',
      params: {
        freshCast: String(Date.now()),
      },
    });
  }

  if (!entitlements.aiReadingsEnabled) {
    return (
      <ScreenContainer scroll={false}>
        <View style={styles.empty}>
          <Text style={styles.title}>Premium Reading</Text>
          <Text style={styles.body}>
            AI-enhanced readings are a premium feature. Manage your version to unlock them.
          </Text>
          <CastButton label="MANAGE VERSION" onPress={() => router.push('/version')} />
        </View>
      </ScreenContainer>
    );
  }

  if (isLoading) {
    return (
      <ScreenContainer scroll={false}>
        <View style={styles.centered}>
          <ActivityIndicator color={aiChingColors.gold} />
        </View>
      </ScreenContainer>
    );
  }

  if (!reading) {
    return (
      <ScreenContainer scroll={false}>
        <View style={styles.empty}>
          <Text style={styles.title}>No premium reading yet</Text>
          <Text style={styles.body}>Cast a hexagram to prepare an AI-enhanced reading.</Text>
          <CastButton label="CAST" onPress={() => router.push('/')} />
        </View>
      </ScreenContainer>
    );
  }

  const backgroundSource = getHexagramBackgroundSource(reading.hexagramNumber, themeId);
  const askedQuestion = reading.question?.trim();
  const selectedPersonality = getAiReadingPersonality(aiReadingPersonalityId);
  const premiumReading = reading.premiumReading;

  return (
    <View style={styles.backgroundScreen}>
      {backgroundSource ? (
        <Image source={backgroundSource} style={styles.backgroundImage} contentFit="cover" />
      ) : null}
      <View style={styles.imageScrim} />
      <SafeAreaView style={styles.readingSafeArea}>
        <ScrollView ref={scrollViewRef} contentContainerStyle={styles.readingContent}>
          <View style={styles.header}>
            <HexagramView lines={reading.lines} size="small" />
            <Text style={styles.date}>{formatReadingDate(reading.localDate)}</Text>
            <Text style={styles.title}>
              Premium Reading: Hexagram {reading.hexagramNumber}: {reading.hexagramName}
            </Text>
          </View>

          <View style={styles.card}>
            <Text style={styles.cardTitle}>{askedQuestion ? 'Your Question' : 'General Outlook'}</Text>
            <Text style={styles.body}>
              {askedQuestion ??
                'You did not ask any particular question, so your reading will reflect a general outlook for you, much like a horoscope might provide.'}
            </Text>
          </View>

          <View style={styles.card}>
            <Text style={styles.cardTitle}>AI Reading Space</Text>
            {premiumReading ? (
              <>
                <Text style={styles.meta}>
                  Voice: {premiumReading.personalityName} | Model: {premiumReading.model}
                </Text>
                <PremiumReadingText text={premiumReading.text} />
              </>
            ) : (
              <>
                <Text style={styles.body}>
                  The oracle is considering your question through {selectedPersonality.name}, this
                  hexagram, its reversed aspect, and its opposite.
                </Text>
                {errorMessage ? <Text style={styles.errorText}>{errorMessage}</Text> : null}
                {isGenerating ? (
                  <View style={[styles.generateButton, styles.generateButtonDisabled]}>
                    <ActivityIndicator color={aiChingColors.ink} />
                    <Text style={styles.generateButtonText}>The Oracle Is Considering...</Text>
                  </View>
                ) : (
                  <Pressable
                    onPress={handleGeneratePremiumReading}
                    style={({ pressed }) => [styles.generateButton, pressed && styles.pressed]}>
                    <Text style={styles.generateButtonText}>
                      {errorMessage ? 'Try Again' : 'Generate Premium Reading'}
                    </Text>
                  </Pressable>
                )}
              </>
            )}
          </View>

          <CastButton label="ASK ANOTHER QUESTION" onPress={handleAskAnotherQuestion} />
        </ScrollView>
      </SafeAreaView>
    </View>
  );
}

const styles = StyleSheet.create({
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  empty: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 18,
    padding: 24,
  },
  backgroundScreen: {
    flex: 1,
    backgroundColor: aiChingColors.ink,
  },
  backgroundImage: {
    ...StyleSheet.absoluteFill,
  },
  imageScrim: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(10, 12, 16, 0.58)',
  },
  readingSafeArea: {
    flex: 1,
  },
  readingContent: {
    flexGrow: 1,
    padding: 24,
    paddingBottom: 112,
    alignItems: 'center',
  },
  header: {
    alignItems: 'center',
    gap: 14,
    marginBottom: 24,
    width: '100%',
  },
  date: {
    color: aiChingColors.gold,
    fontSize: 13,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  title: {
    color: aiChingColors.mist,
    fontSize: 28,
    lineHeight: 36,
    fontWeight: '700',
    textAlign: 'center',
  },
  card: {
    width: '100%',
    maxWidth: 640,
    borderRadius: 8,
    backgroundColor: 'rgba(16, 19, 24, 0.72)',
    borderWidth: 1,
    borderColor: 'rgba(231, 197, 111, 0.18)',
    padding: 18,
    gap: 10,
    marginBottom: 18,
  },
  cardTitle: {
    color: aiChingColors.gold,
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '800',
  },
  meta: {
    color: aiChingColors.muted,
    fontSize: 12,
    lineHeight: 18,
    fontWeight: '700',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  body: {
    color: aiChingColors.mist,
    fontSize: 16,
    lineHeight: 25,
    textAlign: 'center',
  },
  errorText: {
    color: '#ffb4a8',
    fontSize: 14,
    lineHeight: 20,
    textAlign: 'center',
  },
  generateButton: {
    minHeight: 52,
    borderRadius: 8,
    backgroundColor: aiChingColors.gold,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  generateButtonDisabled: {
    opacity: 0.72,
  },
  generateButtonText: {
    color: aiChingColors.ink,
    fontSize: 14,
    lineHeight: 20,
    fontWeight: '800',
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  pressed: {
    opacity: 0.72,
  },
});
